<a href="https://colab.research.google.com/github/vrindaparam/Python-programs/blob/main/Image_Processing_in_Python_2022_06_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is an image?

For the purposes of this workshop, **"an image is an array, or a matrix, of square pixels arranged in columns and rows"**.

---

In a **grayscale** image, the pixel value determies the shade of gray (0 for black, 255 for white)

![grayscale.png](https://miro.medium.com/max/533/1*Ev5QaW5IsjmYa1vzVPniUw.png)

---

In a **colour** image, each pixel has three *channels*, which correspond to Red, Green, and Blue. The intensity of these channels determine how Red, or Green, or Blue the pixel is. Since any other colour can be made out of these three colours, the combination of these channels can create any colour in the human-visible spectrum.

![colour.png](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Pixel_geometry_01_Pengo.jpg/200px-Pixel_geometry_01_Pengo.jpg)

# Image properties

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import requests

from PIL import Image, ImageEnhance

## First look at the image

In [ ]:
img_url = 'https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png'
Image.open(requests.get(img_url, stream=True).raw)

## Saving the image as an array

In [ ]:
img_arr = np.asarray(Image.open(requests.get(img_url, stream=True).raw))

## Checking image dimensions

In [ ]:
img_arr.shape

3 - pixels (RGB)
512*512 - image pixel

##### <font color=yellow>Question </font>   
What information do you get from the shape of the image array?

##### <font color=green><b> Solution </b></font>
Check the contents of `img_arr` to get a hint

In [ ]:
img_arr

##### <font color=yellow>Question </font>   
What is the maximum and minimum brightness an image can have in absolute terms? How do we find the brightness of the image as a percentage?

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
img_arr.mean()*100/255

# Tweaking image properties

We will now change a few image properties like brightness, color, contrast, and sharpness by a factor ranging from 0 to 2.

To do this, we use the Python Imaging Library (`PIL`)'s `ImageEnhance` function. `ImageEnhance`'s `Brightness()`, `Color()`, and `Contrast()`  all load the image; then, we can use their `enhance()` methods to enhance those properties by any factor we choose.

#### Changing Brightness

In [ ]:
plt.figure(figsize=(10, 12))

for i, factor in enumerate(np.linspace(0, 2, 9)):
  plt.subplot(3, 3, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(np.asarray(ImageEnhance.Brightness(Image.fromarray(img_arr)).enhance(factor)))
  plt.xlabel(factor)

plt.suptitle('Changing Brightness', fontsize=20)
plt.tight_layout()
plt.show()

At the pixel level, each pixel is simply multiplied by the factor to get its new value.

In [ ]:
print(f"1st pixel of the original image:\n{img_arr[0, 0]}\n")

print(f"Enhancing brightness by a factor of 0:\n\
{np.asarray(ImageEnhance.Brightness(Image.fromarray(img_arr)).enhance(0))[0, 0]} \
--> Absolute Black\n")

print(f"Enhancing brightness by a factor of 1:\n\
{np.asarray(ImageEnhance.Brightness(Image.fromarray(img_arr)).enhance(1))[0, 0]} \
--> Same as original\n")

print(f"Enhancing brightness by a factor of 2:\n\
{np.asarray(ImageEnhance.Brightness(Image.fromarray(img_arr)).enhance(2))[0, 0]} \
--> Almost White")

##### <font color=yellow><b> Question </b></font>
How will each of the below pixels change if `factor=0` and `factor=255`, and why?

In [ ]:
pixels = np.asarray([[(255, 0, 0), (0, 255, 0), (0, 0, 255)], 
          [(200, 150, 100), (150, 200, 100), (100, 150, 200)],
          [(0, 0, 0), (255, 255, 255), (127, 127, 127)]], dtype=np.uint8)

print(pixels)
plt.imshow(Image.fromarray(pixels));

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
plt.figure(figsize=(15, 10))

for i, factor in enumerate([0, 0.5, 1, 1.5, 2, 255]):
  plt.subplot(1, 6, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  enhanced_pixels = np.asarray(ImageEnhance.Brightness(Image.fromarray(pixels)).enhance(factor))
  plt.imshow(enhanced_pixels)
  plt.xlabel(f"factor={factor}\n{enhanced_pixels}")

plt.tight_layout()
plt.show()

##### <font color=yellow><b> Question </b></font>
How will the below look like if `factor=10`, and why?

In [ ]:
plt.figure(figsize=(12, 15))
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(np.asarray(img_arr));

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
plt.figure(figsize=(12, 15))
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(np.asarray(ImageEnhance.Brightness(Image.fromarray(img_arr)).enhance(10)));

##### <font color=yellow><b> Question </b></font>
Why do we see patches of purple?

##### <font color=green><b> Hint </b></font>
Click below to see a hint

In [ ]:
pixels = np.asarray([[(0, 1, 1), (1, 0, 1), (1, 1, 0)]], dtype=np.uint8)
print(pixels)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(Image.fromarray(pixels));

In [ ]:
enhanced_pixels = np.asarray(ImageEnhance.Brightness(Image.fromarray(pixels)).enhance(255))
print(enhanced_pixels)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(Image.fromarray(enhanced_pixels));

#### Changing Color Intensity (Saturation)

In [ ]:
plt.figure(figsize=(10, 12))

for i, factor in enumerate(np.linspace(0, 2, 9)):
  plt.subplot(3, 3, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(np.asarray(ImageEnhance.Color(Image.fromarray(img_arr)).enhance(factor)))
  plt.xlabel(factor)


plt.suptitle('Changing saturation', fontsize=20)
plt.tight_layout()
plt.show()

Saturation is basically a measure of the relative intensity of colors in an image.  
Decreasing the saturation reduces the difference between the values of individual color channels in a pixel by bringing them closer to their average (i.e., converts the pixel into greyscale).  
Increasing the saturation increases the difference, enhancing the already dominant colors even more.

In [ ]:
print(f"1st pixel of the original image:\n{img_arr[0, 0]}")
print(f"Enhancing color by a factor of 0:\n\
{np.asarray(ImageEnhance.Color(Image.fromarray(img_arr)).enhance(0))[0, 0]} --> \
Colors are brought closer to their average")
print(f"Enhancing color by a factor of 1:\n\
{np.asarray(ImageEnhance.Color(Image.fromarray(img_arr)).enhance(1))[0, 0]}")
print(f"Enhancing color by a factor of 2:\n\
{np.asarray(ImageEnhance.Color(Image.fromarray(img_arr)).enhance(2))[0, 0]} --> \
Colors are brought further apart from their average")

In [ ]:
pixels = np.asarray([[(255, 0, 0), (0, 255, 0), (0, 0, 255)], 
          [(200, 150, 100), (150, 200, 100), (100, 150, 200)],
          [(0, 0, 0), (255, 255, 255), (127, 127, 127)]], dtype=np.uint8)

print(pixels)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(Image.fromarray(pixels));

##### <font color=yellow>**Question** </font>
How will the above pixels change if `factor=0` and `factor=2`, and why?

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
enhanced_pixels = np.asarray(ImageEnhance.Color(Image.fromarray(np.asarray(pixels, dtype=np.uint8))).enhance(0))
print(enhanced_pixels)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(enhanced_pixels);

**Note:** The actual pixel values are not equal to the average as `PIL.ImageEnhance` does not use a direct formula to manipulate pixels, but actually interpolates (blends) the original image with a transformed image by the given factor. [This](https://stackoverflow.com/a/59171242/9792001) stackoverflow answer explains it pretty well with an example.

In [ ]:
enhanced_pixels = np.asarray(ImageEnhance.Color(Image.fromarray(np.asarray(pixels, dtype=np.uint8))).enhance(2))
print(enhanced_pixels)
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(enhanced_pixels);

#### Changing Contrast

In [ ]:
plt.figure(figsize=(10, 12))

for i, factor in enumerate(np.linspace(0, 2, 9)):
  plt.subplot(3, 3, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(np.asarray(ImageEnhance.Contrast(Image.fromarray(img_arr)).enhance(factor)))
  plt.xlabel(factor)

plt.suptitle('Changing Contrast', fontsize=20)
plt.tight_layout()
plt.show()

Contrast is basically the difference in brightness between pixels. Increasing contrast increases this difference, while decreasing contrast decreases it.

Further reading: [Difference between contrast and saturation](https://www.quora.com/What-are-the-differences-between-saturation-and-contrast-in-photography)

In [ ]:
# At the pixel level

plt.figure(figsize=(15, 10))

for i, factor in enumerate([0, 0.5, 1, 1.5, 2, 255]):
  plt.subplot(1, 6, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  enhanced_pixels = np.asarray(ImageEnhance.Contrast(Image.fromarray(pixels)).enhance(factor))
  plt.imshow(enhanced_pixels)
  plt.xlabel(f"factor={factor}\n\nPixels:\n{enhanced_pixels}\n\nStd. deviation:\n{enhanced_pixels.std():.0f}")

plt.tight_layout()
plt.show()

### Flipping and Rotating images

<font color=yellow>**Question:** What is the difference between flipping and rotating an image?</font>  

#### Flipping

For flip, we will use `cv2.flip()`. It takes the image and a value between 0, 1 and -1.  
* For 0, the image is flipped vertically  
* For 1, the image is flipped horizontally
* For -1, the image is flipped both horizontally and vertically

In [ ]:
import cv2

In [ ]:
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(img_arr);

In [ ]:
plt.figure(figsize=(12, 5))

for i, factor in enumerate([0, 1, -1]):
  plt.subplot(1, 3, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(cv2.flip(img_arr, factor))
  plt.xlabel(factor)

plt.suptitle('Flipped images', fontsize=20)
plt.tight_layout()
plt.show()

##### <font color=yellow>**Question** </font>
How will the below image array change for different flips?
```
[[0 1 2]  
 [3 4 5]  
 [6 7 8]]
```

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
pixels = np.asarray([(0, 1, 2), 
                     (3, 4, 5),
                     (6, 7, 8)], dtype=np.uint8)

print(f"Original image pixels:\n{pixels}\n")
print(f"Flipped vertically:\n{cv2.flip(pixels, 0)}\n") 
print(f"Flipped horizontally:\n{cv2.flip(pixels, 1)}\n") 
print(f"Flipped both vertially and horizontally:\n{cv2.flip(pixels, -1)}") 

#### Rotating

Rotating is straightforward. We load the image from the image array and rotate it by as many degrees as we want.  

In [ ]:
plt.figure(figsize=(18, 4))

for i, angle in enumerate([0, 45, 90, 180, 270]):
  plt.subplot(1, 5, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(Image.fromarray(img_arr, 'RGB').rotate(angle))
  plt.xlabel(angle)

plt.suptitle('Rotated images', fontsize=20)
plt.tight_layout()
plt.show()

##### <font color=yellow>**Question** </font>
How will the below image array change if rotated by 90&deg;, 180&deg;, and 270&deg;?
```
[[0 1 2]  
 [3 4 5]  
 [6 7 8]]
```

##### <font color=green><b> Solution </b></font>
Click below to see the solution

In [ ]:
pixels = np.asarray([(0, 1, 2), 
                     (3, 4, 5),
                     (6, 7, 8)], dtype=np.uint8)

print(f"Original image pixels:\n{pixels}\n")
print(f"Rotated 90 degrees:\n{np.rot90(pixels, k=1)}\n") 
print(f"Rotated 180 degrees:\n{np.rot90(pixels, k=2)}\n") 
print(f"Rotated 270 degrees:\n{np.rot90(pixels, k=3)}") 
print(f"Rotated  degrees:\n{np.rot90(pixels, k=5)}") 

# Saving and downloading the image

## Saving the image

In [ ]:
Image.fromarray(img_arr).save("image.jpg")

The saved image will be visible in the file explorer pane on the left.

## Downloading programatically

In [ ]:
from google.colab import files

files.download("image.jpg")

# Wrapping up...

## What we've learnt?
1. Digital representation of an image, and how a monochrome image is different from a coloured one
2. How to perform basic image adjustments like brightness, saturation, contrast, and orientation
3. How to save and download altered images from Google colab.

## Where can this knowledge be used?
1. Enhance/correct your photos without using 3rd party software
1. **Image augmentation:** Increasing the size of your dataset for model training. *How?*



**Siddhant Sadangi** ([LinkedIn](https://www.linkedin.com/in/siddhantsadangi), [Email](mailto:siddhant.sadangi@gmail.com))